### ISSUE TITLE
Data Dump For May 1st?

### ISSUE THREAD

**Issue by ekianjo** [bdefore/protondb-data#13]
Waiting for it :) Thanks

**Comment by bdefore** [comment]
@ekianjo will get this to you today, but probably not for another 6-10 hours. thanks.

**Comment by ekianjo** [comment]
no problem, going to sleep now. I'll check when I wake up

**Comment by bdefore** [comment]
update is now up

**Comment by ekianjo** [comment]
Thanks, my article is here too
https://boilingsteam.com/borderlands-enhanced-version-rocks-on-proton/
