### ISSUE TITLE
ProtonDB needs a rework. Mostly useless in it's current state

### ISSUE THREAD

**Issue by Lalarian** [bdefore/protondb-data#14]
Hello!

I am not talking about a specific game's compatibility here, but about ProtonDB and it's supposed worth.
First, for making my position clear:
By my definition, the intend for Proton is to make Linux as feasible as a gaming platform, as Windows. If it's otherwise than just tell me, and I will never come back here again.

Than there is ProtoDB. A great source for gamers on finding if their favorite game will run on Linux, before reinstalling their system and also good for developers who just want to contribute by improbing support for a game.

In regards to Proton's purpose this means, that game ratings on ProtonDB should reflect an average user's position.
The type of user that previously played on Windows or even on Console and who wants to play a game within 5 minutes after installation.
From ProtonDB's own definition, the rating scheme is as follows:

Platinum: Runs perfectly out of the box
Gold : Runs perfectly after tweaks
Silver : Runs with minor issues, but generally is playable
Bronze : Runs, but often crashes or has issues preventing from playing comfortably
Borked : Either won't start or is crucially unplayable

So as an example I now take the game "Civilization 4 (3900)" for consideration.
(https://www.protondb.com/app/3900)
If you read the issues thouroughly, or even tried it youself, you can easily tell that the game is by fact not playable using Proton, yet. You will inevitably come to the point where your screen becomes black and you can't see anything. Not even after saving and reloading the game.
Not being able to progress in a game from a certain point is no minor problem for sure, but it's game breaking.
So there's no doubt that this behaviour matches the definition of "Borked" in the meaning that most people will never be able to finish this game using Proton. (Borked : Either won't start or is crucially unplayable).
But still the game got an overall "silver" rating, telling people who are in search for this game, and also people who are at general probing on gaming on Linux, that there should be no problem preventing a playthrough. then they try and will be very disapointed, for saying the least. For sure this discrepancey will vastly hurt the reputation of Proton and gaming on Linux.

Of course this isn't an issue only for this game. In all games that don't run perfectly are affected by this. I think it's obvious why this happens. The average Linux users is far more experienced than the average Windows user or even console gamer. Many people just write a solution they found after fiddling around, or searching the web for hours and proceeding with trial and error until they have worked around the bug. But this clearly does not comply to the definition of ProtonDB. Although those people are clever enough, for solving the problem, they aren't clever enough for remembering what Proton is intended to be. Also many might be just so happy about running this Windows game on their Linux machine, that they submit their rating based on their personal feeling instead of the official definition of ProtonDB.

So I take it for proven, that most ProtonDB submitters are not able for using the rating scheme as it was intended.

Thats why I suggest a major rework. It should be simplified, for giving evaluable results.
All existing entries should be converted into a new rating scheme, with just two options.
Either:
a) The game runs and is possible to play through, with no fiddling outside maybe Steam options.
b) It doesn't

Otherwise I don't see that ProtonDB will be of any worth for long, because in it's current state it lacks reliabililty for the vast majority of games and users, thus makeing for a loss of the intended prupose.

Thank you!

**Comment by shrubdroid** [comment]
I'm afraid your suggestion oversimplifies the rating system. Essentially, it's already there. "The game runs and is possible to play through, with no fiddling outside maybe Steam options" is a platinum rating. "It doesn't" is everything below platinum. 

An example is King's Quest. It is listed as bronze, which is accurate if no tweaks are made. But, the game can be made to run perfectly when using Proton 3.7-8 after some tinkering with the profile, which is a gold rating. Just saying "It doesn't" right up front implies that it absolutely will not work, which isn't true. Getting a game designed to run under Windows to run under Linux is not a simple task, so there are bound to be games that can possibly work after some tinkering, which is why there is a multi-layered rating system along with a section for reporting what tweaks are needed to make it work.

Unfortunately, the rating system can only be as good as the people using it, so there are going to be cases where people report misleading things.

**Comment by Lalarian** [comment]
Too bad that I messed the answer here, and that there wasn't more response, because my point is not only important, but completely justified.
Yes, I think it's needed to simplify the rating system vastly and no, this would not be oversimplifying at all. As you can easily see at the moment, the rating database if full with at least 30% absolute wrong and misleading ratings. People that rate games and software as platinum, after they fiddled for hours, without even giving a detiled explanation on how they achieved to run somethin. So there's an extremely huge amount of worthless rating. This is proof that most people are not able to comply with the current rating system, and so my suggestion would abolultely not oversimplify the rating system, but it would totally adapt it to standr human capabilites and behaviour.

**Comment by bdefore** [comment]
@Lalarian i apologize for the uncommunicated closing of the PR here. your points are valid, and thanks for writing them up. work is ongoing to renovate the reporting system and scoring heuristic which hopefully will address many of the things you mentioned here.

**Comment by Lalarian** [comment]
Wow, this was fast. You answered before I could correct all these mistakes in my answer.
Thank you for explanation and reaction, I am hoping for a bright future for Linux gamign now! :)

**Comment by bdefore** [comment]
https://www.protondb.com/news/one-year-of-protondb @Lalarian 

This does not yet address all that you have mentioned here, but I hope you see it as a step in the right direction.

**Comment by Lalarian** [comment]
Thank you very much!
Ideed I see this as a vast improvement. My idea was just one suggestion for avoiding that common problem of irrelevance in rating.
It's great that you acknowledged tand adressed the problem, and found a potential solution., that's perhaps better than my idea was.
We will see, what times brings :)
