### ISSUE TITLE
Website: make it possible to delete our own reports

### ISSUE THREAD

**Issue by CoralineCastell** [bdefore/protondb-data#17]
Sometimes we write a ProtonDB review and then realize it's inaccurate or that a workaround has been found since we last ran into a given problem. 

The current inability to delete one's own reports does not reflect the flexibility present in Steam Play's own fast-paced development, does not account for human error, and could be negatively weighing down the report system.

Although one could argue that a `borked` review was accurate at the time of posting, if a fix has been issued a short time afterwards the report it essentially warranted useless. Even if the same author then decides to post a new `gold` report, the `borked` one is still weighing down on the game's ratings with no indication that the same author has now been able to fix their issue. The same is true for reversed scenarios.

Finally, I essentially double-posted a Proton report, and that's what prompted me to request this feature. Upon suddenly realizing my first report was unclear, I penned a new one a few seconds afterwards. Both reports are now up, with no way of removing either one of them.

I think ProtonDB could be greatly improved by making its report system more flexible, and I think this is one simple and effective way to work towards that goal.

**Comment by supertin** [comment]
Agree - I posted a report for a game last Friday night, and by Saturday morning, I found out I was wrong on a few points. While I can see benefits to keeping old reports when new versions of software appear, the user changes distro, etc, it's not helpful to keep information the user discovers is incorrect.

Registered users should be allowed to edit their own reports. If the current inability to edit is based on a desire to keep old data, editing could be limited to a few days or a week to allow users some time to tweak their settings before locking in the reports.

**Comment by fallenguru** [comment]
As I understand it, if you submit a new report any earlier ones won't count towards the rating any longer. So if you managed to get it running, even shortly after, you can just submit a new report. In this case it'd be nice for the earlier report to be marked as superseded. But then you could just have changed hardware, or distro, or even just mesa branch, ... and I think that should count as an entirely new report.
Maybe count one report per user and hardware configuration and visually distinguish (greyed out, not displayed by default, ...) all superseded ones?

Actual errors & omissions are another issue, for those, deletion (within x hours) would be easiest. Can always resubmit, after all. That and/or manually marking a review as superseded. Have the user select from a list of valid reasons ("invalid data", "PEBKAC", ...) and display them alongside the original report. Auto-superseded ones could have "newer version available" and/or "older than x months", then.

**Comment by bdefore** [comment]
thanks for the suggestions. let me first reiterate that as @fallenguru mentions, reports made by contributors known to have submitted for the same game are considered superseded and are not counted towards protondb's rating.

the current reporting flow is undergoing a change that will address many weaknesses of the current system, and will also clear up duplicates better as well as include moderation tooling so that reports can be flagged or retired on demand via our discord channel. that's not meant to be as complete a  solution as requested here, so some time after its release i'll be revisiting how users themselves can edit their own reports.

**Comment by CoralineCastell** [comment]
> the current reporting flow is undergoing a change that will address many weaknesses of the current system, and will also clear up duplicates better as well as include moderation tooling so that reports can be flagged or retired on demand via our discord channel.

Thanks for your reply. I'm sure I'm not alone in saying it's great to hear the matter is being looked into. However, as someone who supports FOSS over the alternative and safeguards her privacy, I don't use Discord. On the long run, please open other communication channels that aren't tied to using proprietary software or going through sign-up processes to address report issues. Maybe an e-mail would do?

Keep up with the great work.

**Comment by bdefore** [comment]
@CoralineCastell i have some good news for you:

- our moderators can now delete reports upon request
- some of them prefer to hang out on freenode #protondb channel

no self-service yet.

**Comment by CoralineCastell** [comment]
@bdefore thanks so much for your continuous work on improving Proton! I'm thrilled at the news and have already noticed some changes on the website over the last few days. I'll look into contacting the mods via the freenode channel and will update my request accordingly upon the successful deletion of my erroneous report.

**Comment by NoXPhasma** [comment]
@CoralineCastell your report will be removed on the next update cycle.

**Comment by CoralineCastell** [comment]
My report has been removed and believe others can now request for theirs to be removed as well. I'm considering the issue closed.

**Comment by JamesTheAwesomeDude** [comment]
@bdefore, can you re-open this, or should we start a new issue?

By no means is `Website: make it possible to delete our own reports` resolved at this time…

**Comment by LeSnake04** [comment]
https://github.com/bdefore/protondb-data/issues/33

I opened a new issue for this

**Comment by neyel8r** [comment]
not sure why this isn't possible without having to contact a mod

**Comment by KeebWasTaken** [comment]
I agree with the hardware changing aspect of the dev's argument, however.
When this site relies so hard on getting things right, and the inability to edit previous information that may have been misinformed or just forgetting the basics, People will come across bad information. 

When deleting a post, It should clearly prompt you that hardware/OS & software changes will change how a game behaves to various things. I don't want to have information previously posted misinform someone, no matter the likelihood of it being found over everyone else's posts.

by no means am I a programmer, UX designer, Database Manager etc. so feel free to correct my opinion if you think what we have is fine and justifiable, just keep it civil.

**Comment by Fhraze** [comment]
I think I made the worst possible report to protondb and I can't delete it, how cool

**Comment by RTbecard** [comment]
I have a suggestion... If you want to keep deleting reports as a mod implemented task...  Could you add a "request removal" link for all reports a user has submitted on their profile.

It could then have a text box where we could explain why we want it removed, then it would be forwarded onto a mod to-do list.

Additionally, i think having a _you can still edit within the first 24 hours of submitting_ feature would be great, and still line up with you goals here.
