### ISSUE TITLE
Unable to submit game report - "There was an error during submission. Please let us know how this happened!"

### ISSUE THREAD

**Issue by julienbenjamin** [bdefore/protondb-data#20]
First, I need to let you know that my Steam account is linked to protondb.com when trying to submit a new report.

I can go through the whole process but, when clicking on the last "Next" button at the stage "Preview" when submitting my report, a drop-down box displays the following : 
> www.protondb.con says 
> There was an error during submission. Please let us know how this happened!"

For the record, I am using a PiHole but AFAIK, it does not block anything related to ProtonDB.

Edit: I tried again with all settings of my Steam profile set to public and I could submit a report. I think there is an bug to handle whenever someone is logged and protondb cannot access via Steam API the game library details. I also notice that the AppID disappeared to display the full name of the game for which the report is being written.

**Comment by Alexander88207** [comment]
Is the problem still there?

**Comment by bdefore** [comment]
@julienbenjamin @Alexander88207 this should be fixed as of two days ago. game library details being private no longer breaks submission.

**Comment by Alexander88207** [comment]
Then this can be closed :grinning:?

**Comment by julienbenjamin** [comment]
It seems to work, so, yes this can be closed.
