### ISSUE TITLE
Nov2020 data - No Dec1 tar?

### ISSUE THREAD

**Issue by ekianjo** [bdefore/protondb-data#31]
Hi @bdefore, I saw that 5 hours ago you update the Nov1 tar archive, but shouldn't that be the dec1 tar archive instead? Is that an issue with the name, or is it simply that you updated last month's data dump and Dec1 data dump is not available as of now?

**Comment by bdefore** [comment]
sorry @ekianjo i did mistakenly replace the previous update. if you've previously looked at the 'reports_nov1_2020.tar.gz' file it is identical with what is now 'reports_dec1_2020.tar.gz' and the previous file has been restored. thanks for pointing out!
