### ISSUE TITLE
march update delay

### ISSUE THREAD

**Issue by bdefore** [bdefore/protondb-data#40]
I'm heads down on Steam Deck support and the data structure of reports has changed in February, so this month's update will be a bit delayed. I've made a snapshot for today and will publish when I can. Subscribe here if you're waiting for it and I'll comment when it's ready.

**Comment by ekianjo** [comment]
thanks for the info @bdefore will be waiting for the snapshot

**Comment by ekianjo** [comment]
will you also explain somewhere how the data structure has changed?

**Comment by bdefore** [comment]
@ekianjo the march 2022 update is now in the repo. note that this only includes reports up to march 1. i've added some notes explaining the data structure changes to the readme (https://github.com/bdefore/protondb-data/blob/master/reports/README.md), but let me know if something else looks different that i may have forgotten.
