### ISSUE TITLE
Please make the site opensource

### ISSUE THREAD

**Issue by tim241** [bdefore/protondb-data#5]
it'd be great (and transparent) if https://www.protondb.com/ would be opensource.

**Comment by tuxayo** [comment]
Yes, this is a too much valuable tool to risk loosing it if the main dev cannot maintain or host it anymore.

**Comment by tuxayo** [comment]
Also that will allow for localization because not everyone understands english well enough.

**Comment by tuxayo** [comment]
That will also allow someone else to build a similar tool for Lutris or Wine in general for example. In the case this is not in the scope of this project or the main dev doesn't have the resources to do this.

**Comment by dreamer** [comment]
I'll just chip in and remind maintainer, that open-sourcing was promised on day 1.

**Comment by julienbenjamin** [comment]
> Yes, this is a too much valuable tool to risk loosing it if the main dev cannot maintain or host it anymore.

It is already a problem when the dev is on vacation (like these days) and reports cannot be submitted on my end for a problem that cannot be even troubleshooted.

**Comment by bdefore** [comment]
The answer to this has always been 'not at this time' and unlike what dreamer_ has said, no commitment or 'promise' was ever made otherwise.

Reposting from when it came up a month ago:

> A project as a sole contributor is very different than being a maintainer of a community managed open source one. I've experienced both. There are features I have in mind that would most efficiently be pursued solo rather than documenting code, triaging / debating priorities, reviewing PR's with potentially fragmented forks. That's a lot of labor! I'll candidly admit I could swing another way on this in the future and only want the best for the community, but for the goals ahead I think that's best chased independently with an attentive ear to feedback.

I'll now close this issue since a Github issue on the data export repo is an inefficient place to have this discussion. Please reach out on Discord if this is important to you.

**Comment by tuxayo** [comment]
> most efficiently be pursued solo rather than documenting code, triaging / debating priorities, reviewing PR

It can still be a solo project. The most important thing isn't being a community project. But having the code libre somewhere.
No need for documentation, bug tracker, accepting patches. Sure that would be nice but it's perfectly fine to not have the ressources for dealing with that.

> Please reach out on Discord if this is important to you.

Sorry I don't have Discord for the same reasons I'm trying to use as much as possible libre stuff ^^"
