### ISSUE TITLE
Website: rare text

### ISSUE THREAD

**Issue by Voligoma** [bdefore/protondb-data#52]
This might not be an issue but in the image below is the text "Borked" is being misspeld by "Broken"? Or is something that i am not understanding. 
![image](https://github.com/user-attachments/assets/06c8fd82-2593-4e40-a70c-c77500b3b88e)

**Comment by firefly2442** [comment]
"Borked" is slang for not working properly or broken.

**Comment by Voligoma** [comment]
Oh ok thank you for the expalnation, english its not my native language so i didn´t understand it.
