### ISSUE TITLE
Search inconsistent/not reliable

### ISSUE THREAD

**Issue by Termuellinator** [bdefore/protondb-data#9]
For few weeks now i'm noticing that the search won't return results for games anymore (examples i just tested: trailmakers, divinity original sin 2, Vermintide). If you search by App-ID they show up.
Tested with multiple browsers.
Anyone else can confirm? And i Hope this is the right place for this? ^^

**Comment by bdefore** [comment]
We don't have a repo yet for website issues, so feel free to ask here.

There appears to be data inconsistency from the API we use for search (SteamDB Instantsearch - note this is distinct from the full SteamDB site). I'll copy paste a note from our Discord:

```
search is missing some results. note that protondb uses steamdb's instantsearch feature for these, so it's not something we control directly. if it's not coming up in results at https://steamdb.info/instantsearch it won't show up in protondb. while i investigate, remember you can use the same app id from steam for protondb urls, for example, hellblade on steam is https://store.steampowered.com/app/414340 and on protondb is https://www.protondb.com/app/414340
```

**Comment by bdefore** [comment]
The latest release fixes an issue with searches that had spaces in them. I believe this fixes the issue apart from the issue I mention above with SteamDB's data. Closing for now but feel free to reopen if you have a specific case.
